event/urls.py
from django.urls import path
from . import views

app_name = 'event'

urlpatterns = [
    path('', views.eventIndex, name='eventIndex'),
    path('addEvent/', views.getEvent, name='getEvent'),
    path('addMember/<int:pkTarget>/', views.getMember, name='getMember'),
    path('/<int:pkTarget>', views.deleteMember, name='deleteMember'),
]

homepage/urls.py
from django.urls import path, register_converter
from . import views, converters

app_name = 'homepage'

register_converter(converters.NegativeIntConverter, 'negint')

urlpatterns = [
    path('', views.index, name='index'),
    path('skills/', views.skills, name='skills'),
    path('#desc', views.index, name='index'),
    path('clock/<negint:code>/', views.clock, name='clock'),
    path('clock/', views.clock, name='clock'),

]

matkul/urls.py
from django.urls import path
from . import views

app_name = 'matkul'

urlpatterns = [
    path('add/', views.formMatkul, name='formMatkul'),
    path('result/', views.resultMatkul, name='resultMatkul'),
    path(r'^matkuldetails/(?P<pkTarget>)/$', views.detailsMatkul, name='detailsMatkul'),
    path(r'^result/(?P<pkTarget>)/$', views.deleteMatkul, name='deleteMatkul'),
]

oldver/urls.py
from django.urls import path
from . import views

app_name = 'oldver'

urlpatterns = [
    path('', views.index, name='index'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('oldver/', include('oldver.urls')),
    path('form/', include('matkul.urls')),
    path('event/', include('event.urls')),
]

event/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
class Event(models.Model):
    nama = models.CharField('Nama event', max_length=50)
    deskripsi = models.TextField()

    def __str__(self):
        return self.nama

class Member(models.Model):
    nama = models.CharField('Nama', max_length=25)
    event = models.ForeignKey('Event', on_delete=models.CASCADE)

    def __str__(self):
        return self.nama

homepage/models.py
from django.db import models

# Create your models here.

matkul/models.py
from django.db import models
from django.forms import ModelForm
from django.core.validators import MinValueValidator, MaxValueValidator

class Matkul(models.Model):
    nama = models.CharField(max_length=50)
    dosen = models.CharField(max_length=50)
    sks = models.IntegerField(validators=[MinValueValidator(0)])
    deskripsi = models.CharField(max_length=1500)
    semester = models.CharField(max_length=20)
    kelas = models.CharField(max_length=50)

class MatkulForm(ModelForm):
    class Meta:
        model = Matkul
        fields = ['nama', 'dosen', 'sks', 'deskripsi', 'semester', 'kelas']

class Tugas(models.Model):
    x = models.ForeignKey(Matkul, on_delete=models.CASCADE)
    namaDeadline = models.CharField(max_length=50)
    matkul = models.CharField(max_length=50)
    dueToDL = models.IntegerField()

oldver/models.py
from django.db import models

# Create your models here.

event/forms.py
from django import forms
from django.forms import ModelForm
from .models import Event, Member

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['nama', 'deskripsi']

class MemberForm(ModelForm):
    class Meta:
        model = Member
        fields = ['nama']

event/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import Event, Member
from .forms import EventForm, MemberForm
from django import forms

# Create your views here.
def eventIndex(request):
    dataEvent = Event.objects.all()
    dataMember = Member.objects.all()

    return render(request, 'event.html', {'event':dataEvent, 'member':dataMember})

def getEvent(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('event:eventIndex')
    
    else:
        form = EventForm()
    
    return render(request, 'addEvent.html', {'form':form})

def getMember(request, pkTarget=0):
    if request.method == 'POST':
        form = MemberForm(request.POST)
        if form.is_valid():
            form = Member(nama=form.data['nama'], event=Event.objects.filter(pk=pkTarget)[0])
            form.save()

            return redirect('event:eventIndex')
    
    else:
        form = MemberForm()
    
    return render(request, 'addMember.html', {'form':form})

def deleteMember(request, pkTarget):
    target = Member.objects.filter(pk=pkTarget)
    target.delete()

    dataMember = Member.objects.all()

    return redirect('event:eventIndex')

homepage/views.py
from django.shortcuts import render
import datetime


def index(request):
    return render(request, 'index.html')

def skills(request):
    return render(request, 'skills.html')

def clock(request, code=0):
    return render(request, 'clock.html', context={'value':datetime.datetime.now() + datetime.timedelta(hours=code)})

matkul/views.py
from django.shortcuts import render, redirect
from django.core.serializers import serialize
import json
from .models import Matkul, MatkulForm, Tugas

def formMatkul(request):   
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        
        if form.is_valid():
            form.save()

            return redirect('matkul:formMatkul')
        
    else:
        form = MatkulForm()


    return render(request, 'form.html', {'form': form})

def resultMatkul(request):

    data = Matkul.objects.all()
    x_data = json.loads(serialize('json', data))

    return render(request, 'result.html', {'data':x_data})

def detailsMatkul(request, pkTarget):
    details = Matkul.objects.filter(pk=pkTarget)
    detailsTarget = json.loads(serialize('json', details))

    tugasMatkul = Tugas.objects.all().order_by('dueToDL')

    return render(request, 'details.html', {'details':detailsTarget})

def deleteMatkul(request, pkTarget):
    target = Matkul.objects.filter(pk=pkTarget)
    target.delete()

    x_data = json.loads(serialize('json', Matkul.objects.all()))

    return redirect('matkul:resultMatkul')

oldver/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'oldver.html')

event/templates/addEvent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add event!</title>
</head>
<body>
    <form action="#" method="POST" class="form-group" style="margin-top: 5%;">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit">
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

event/templates/addMember.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add member!</title>
</head>
<body>
    <form action="#" method="POST" class="form-group" style="margin-top: 5%;">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit">
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

event/templates/event.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewporatent="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Event!</title>
</head>
<body>
    
    <a href="{% url 'event:getEvent' %}" style="text-align: center;">
        <h2 style="margin-top: 2%;">ADD EVENT!</h2>
    </a>
    <br>
    {% for dataEvent in event %}
    <div style="display: flex; flex-direction: column; border: 2px solid black; margin: 2%; padding: 1%; border-radius: 30px;">
        <div style="text-align: center;">
            <h3>{{dataEvent.nama}}</h3>
            <p><strong>{{ dataEvent.deskripsi }}</strong></p>
            <br>
            {% for dataMember in member %}
                {% if dataMember.event == dataEvent %}
                    <p style="margin: 0; font-size: larger;">{{ dataMember.nama }}</p>
                    <div style="margin-bottom: 1%;">
                        <a href="{% url 'event:deleteMember' pkTarget=dataMember.pk %}">Delete this member</a>
                    </div>
                    <br>
                {% endif %}
            {% endfor %}          
        </div>
        <a href="{% url 'event:getMember' pkTarget=dataEvent.pk %}" style="display: flex; justify-content: center;">
            <button class="btn btn-success">Register</button>
        </a>
    </div>
    {% endfor %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sae Pasomba</title>
</head>
<body>
  <div id="page-container">
    <div id="content-wrap">
    <br>
    {% include 'includes/navbar.html' %}

    {% block body %}

    {% endblock %}

    {% include 'includes/footer.html' %}
</div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    
  </body>
</html>

homepage/templates/clock.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
<div class="display-3" style="text-align: center; color: aliceblue;">
{{ value|time:"H:i" }}
</div>
{% endblock %}

homepage/templates/includes/footer.html
{% load static %}

<div class="social-media">
    <table align="center">
        <tr>
            <td><a href="https://www.instagram.com/saepasomba"><img src="{% static 'instagram-logo.png' %}"></a></td>
            <td><a href="https://twitter.com/saepasomba"><img src="{% static 'twitter-logo.png' %}"></a></td>
            <td><a href="https://www.facebook.com/saepasomba"><img src="{% static 'facebook-logo.png' %}"></a></td>
            <td><a href="https://wa.me/6287884314147?text=Hai%20ganteng"><img src="{% static 'whatsapp-logo.png' %}"></a></td>
        </tr>
    </table>
</div>

homepage/templates/includes/navbar.html
<div class="container">
    
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark d-flex flex-column align-items-center fixed pagenav">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="/"><p>Home</p> <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/#desc"><p>Profile</p></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/skills"><p>Skills</p></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'matkul:formMatkul' %}"><p>Matkul form!</p></a>
              </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'event:eventIndex' %}"><p>Add event!</p></a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'oldver:index' %}"><p>Previous version</p></a>
              </li>
          </ul>
        </div>
      </nav>

      <script>
          
      </script>
</div>

homepage/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

    <div class="name-pict">
        <table align="center">
            <tr>
                <td rowspan="3" align="center"><img class=".img-responsive" src="{% static 'Sae Pasomba.jpg' %}"></td>
                <td class="name">Sae Pasomba</td>
                <td class="empty-cell" style="width: 4%;"><br></td>
            </tr>
            <tr>
                <td class="empty-cell"></td>
            </tr>
        </table>
    </div>

    <div class="profile">
        <div class="square"></div>

    <h3>Fasilkom UI 2019</h3>
    <h3>Ilmu Komputer</h3>
    <h5>1906350862</h5>

    <div class="square"></div>
    </div>

    <br>

    <div class="description" id="desc">
        <p>Sae Pasomba merupakan nama yang diberikan oleh kedua orang tua saya sejak kelahiran saya di Palangka Raya, 24 Februari 2002. Saya sangat menyukai hujan. Menurut saya, hujan membawa suasana menenangkan.</p>
        <div class="square"></div>
        <h5>Hobi</h5>
        <h4>Mengamati hujan</h4>
    </div>

    <br>
    <br>
    <br>

    <div class="riwayat-pendidikan">
        <table align="center">
            <tr>
                <td class="pend1">SD</td>
                <td class="empty-cell"></td>
                <td class="pend1">SMP</td>
                <td class="empty-cell"></td>
                <td class="pend1">SMA</td>
            </tr>
            <tr>
            </tr>
            <tr>
                <td class="pend2">
                    <h4>SDN Percobaan Palangka Raya</h4>
                    <h5>2007 - 2013</h5>
                </td>
                <td class="empty-cell"></td>
                <td class="pend2">
                    <h4>SMP Golden Christian School</h4>
                    <h5>2013 - 2016</h5>
                </td>
                <td class="empty-cell"></td>
                <td class="pend2">
                    <h4>SMA Kharisma Bangsa</h4>
                    <h5>2016 - 2019</h5>
                </td>
            </tr>
        </table>
    </div>

    <br>
    <br>

    <div class="quote1">
        <div class="square"></div>
        <h3>Be a beast!</h3>
    </div>


    <!-- Button trigger modal -->
    <div style="text-align:center;">
        <button type="button" class="btn btn-danger align-self-center" data-toggle="modal" data-target="#exampleModal">
            See Some Photos
        </button>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Random Photos for PPW. From Sae with love</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
            
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="https://vw-photoclassforyou.storage.googleapis.com/images/2019-ChallengeClass1Sq.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="https://betterstudio.com/wp-content/uploads/2019/05/1-1-instagram-1024x1024.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="https://pbs.twimg.com/profile_images/1126625068564402176/VV114FWs_400x400.png" alt="Third slide">
                    </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                    </a>
                </div>

            </div>
        </div>
        </div>
    </div>
    </div>

{% endblock %}

matkul/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Result</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    
    {% include 'includes/navbarForm.html' %}

    <table class="table table-dark" style="text-align: center;">
        <tr>
            <th>Matkul</th>
            <th>Dosen</th>
            <th>Jumlah SKS</th>
            <th>Semester</th>
            <th>Kelas</th>
            <th>Deskripsi</th>
        </tr>
        {% for hasil in details %}
        
        <tr>
            <td><a href="{% url 'matkul:detailsMatkul' pkTarget=hasil.pk  %}">{{ hasil.fields.nama }}</a></td>
            <td>{{ hasil.fields.dosen }}</td>
            <td>{{ hasil.fields.sks }}</td>
            <td>{{ hasil.fields.semester }}</td>
            <td>{{ hasil.fields.kelas }}</td>
            <td>{{ hasil.fields.deskripsi }}</td>
            <br>
        </tr>
        {% endfor %}
    </table>
    <!-- <table>
        {% for tugas in allTugas %}
        <tr>
            <td>{{ tugas.namaDeadLine }}</td>
            <td>{{ tugas.matkul }}</td>
            <td>{{ tugas.dueToDL }}</td>
        </tr>
        {% endfor %}
    </table> -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

matkul/templates/includes/navbarForm.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'matkul:formMatkul' %}">Form</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'matkul:resultMatkul' %}">Result</a>
        </li>
      </ul>
    </div>
  </nav>

matkul/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Result</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>

    {% include 'includes/navbarForm.html' %}

    <div style="margin: 0 auto;">
        <table class="table table-dark" style="text-align: center; margin: 0 0;">
            <tr>
                <th>Matkul</th>
                <th>Dosen</th>
                <th>Jumlah SKS</th>
                <th>Kelas</th>
                <th>Misc</th>
            </tr>
            {% for hasil in data %}
            
            <tr>
                <td><a href="{% url 'matkul:detailsMatkul' pkTarget=hasil.pk  %}">{{ hasil.fields.nama }}</a></td>
                <td>{{ hasil.fields.dosen }}</td>
                <td>{{ hasil.fields.sks }}</td>
                <td>{{ hasil.fields.kelas }}</td>
                <td><a href="{% url 'matkul:deleteMatkul' pkTarget=hasil.pk %}">DELETE</a></td>
                <br>
            </tr>
            {% endfor %}
        </table>
    </div>



    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

oldver/templates/includes/navbar_old.html
<div class="container">
    
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark d-flex flex-column align-items-center fixed pagenav">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:index' %}"><p>Current version</p></a>
            </li>
          </ul>
        </div>
      </nav>

      <script>
          
      </script>
</div>